version: "3.7"
services:
    app:
        build:
            args:
                user: valerie
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-blog
        container_name: laravel-blog-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-blog
        ports:
            - "5173:5173"
    db:
        image: mysql
        container_name: laravel-blog-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3878:3306"
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
        networks:
            - laravel-blog

    nginx:
        image: nginx:alpine
        container_name: laravel-blog-nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel-blog

networks:
    laravel-blog:
        driver: bridge
volumes:
    db_data:
